-- [beforeClass]
DROP TABLE IF EXISTS EQL_IN;
CREATE TABLE EQL_IN (ID INT, NAME VARCHAR(10));
INSERT INTO EQL_IN VALUES(1, 'AA');
INSERT INTO EQL_IN VALUES(2, 'BB');
INSERT INTO EQL_IN VALUES(3, 'CC');

-- [test]
SELECT NAME FROM EQL_IN WHERE ID IN (/* in _1 */)


-- [testDynamic]
SELECT NAME FROM $$ WHERE ID IN (/* in _1 */)


-- [testMap]
SELECT NAME FROM EQL_IN WHERE (ID, NAME) IN (/* in _1 */)